name: Node.js build
on: [pull_request, push]
jobs:
  build:
    name: Node.js v${{ matrix.node-version }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js v${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Update npm
      run: npm install -g npm
    - name: Install dependencies
      run: npm install
    - name: npm ls
      run: npm ls
    - name: Test
      run: npm test
      env:
        CI: true
